### ISSUE TITLE
Route binding and auth middleware

### ISSUE THREAD

**Issue by hmercy** [mmghv/lumen-route-binding#8]
**Stack:** `laravel/lumen-framework: 5.8.12, mmghv/lumen-route-binding: 1.4.2`

I enabled the auth middleware in my project using the `TokenGuard`. In bootstrap/app.php:
```php
$app->routeMiddleware([
    'auth' => App\Http\Middleware\Authenticate::class
]);
```
In routes/web.php:
```php
$router->group(['middleware' => 'auth'], function ($route) {
    $route->get('/posts/{post}', 'PostController@show');
    ...
});
```
The problem is, the code looks for the post object before checking if there is an authenticated user.

Is there a way for the auth middleware to execute first instead of the route binding so it would throw an AuthenticationException without querying for the model?

This has been solved in Laravel using SubstituteBinding middleware: [#6118](https://github.com/laravel/framework/issues/6118)

**Comment by mmghv** [comment]
Unfortunately, there's nothing we can do about that (right now at least).

I actually tried implementing the `middleware` approach for resolving the bindings, And it worked but, you still couldn't control when the bindings are resolved because Lumen doesn't have the `middlewarePriority` option which Laravel uses to control the order of middlewares execution. they actually added it for the sole purpose of solving this issue.

The best you can do now is disable `route-model-binding` for routes with `auth` middleware and fetch models yourself.
